// Generated by CoffeeScript 1.6.1
/*
@CLASS UTILITY
@property v, String|Integer|Boolean value
@description chainable
*/

var U,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

U = function(v) {
  var ut;
  ut = (function() {

    function ut(initValue) {
      this.initValue = initValue != null ? initValue : null;
      this.v = initValue;
      this.cache = {};
      this.settings = {};
      this.settings.localstorage = !!(__indexOf.call(window, 'localStorage') >= 0 && window['localStorage'] !== null);
      this.settings.storgeCompressor = typeof LZString !== 'undefined';
      this.registerEvts = {};
    }

    /*
    # check type of the stored value
    */


    /* =====================================================================
    */


    ut.prototype.is = function(type) {
      var getType, types;
      getType = function(thing, prime) {
        return Object.prototype.toString.call(thing);
      };
      types = {
        'array': '[object Array]',
        'string': '[object String]',
        'object': '[object Object]',
        'win': '[object Window]',
        'doc': '[object HTMLDocument]',
        'function': '[object Function]'
      };
      this.v = types[type] === getType(this.v);
      return this;
    };

    /*
    # EVENTS callbacks
    */


    /* =====================================================================
    */


    ut.prototype.on = function(n, cb) {
      return this.registerEvts[n] = cb;
    };

    ut.prototype.fire = function(n, data) {
      return this.registerEvts[n](data);
    };

    ut.prototype.val = function() {
      return this.v;
    };

    /*
    # Storage
    */


    /* =====================================================================
    */


    ut.prototype.setStore = function(k, v, param) {
      var storage, value;
      value = {};
      if (param) {
        value[exp] = param.expire ? param.expire + this.time() : null;
        storage = param.driver ? param.driver : localStorage;
      }
      if (this.settings.localstorage) {
        value[value] = v;
        if (this.settings.storgeCompressor) {
          value[value] = LZString.compress(v);
        }
        return window[storage][k] = JSON.stringify(value);
      }
    };

    ut.prototype.getStore = function(k, driver) {
      var val;
      if (this.settings.localstorage) {
        return val = this.settings.storgeCompressor ? LZString.decompress(localStorage[k]) : JSON.parse(localStorage[k]);
      }
    };

    ut.prototype.delStore = function(k, driver) {
      if (this.settings.localstorage) {
        return delete localStorage[k];
      }
    };

    /*
    # Dates
    */


    /* =====================================================================
    */


    ut.prototype.date = function() {
      var _ref;
      return (_ref = cache.date) != null ? _ref : cache.date = new Date();
    };

    ut.prototype.time = function() {
      return +date();
    };

    ut.prototype.hasExpired = function(exp) {
      return (exp < this.time() ? true : false);
    };

    ut.prototype.setDay = function(days) {
      this.date();
      return cache.date.setTime(cache.date.getTime() + days * 24 * 60 * 60 * 1000);
    };

    ut.prototype.getDate = function() {
      this.date();
      return cache.date.toGMTString();
    };

    return ut;

  })();
  return new ut(v);
};
